PROGRAM TAREA_3_DEA
IMPLICIT NONE
!DEFINICIÓN DE LAS VARIABLES
!T: PERIODO 
!I: NÚMERO DE DATOS
!M:MASA
!K:RIGIDEZ
!C: COEFICIENTE DE AMORTIGUAMIENTO
!BETA:COEFICIENTE BETA
!GAMA:COEFICIENTE GAMA  
!W: FRECUENCIA NATURAL
!DT: DIFERENCIAL DE TIEMPO
!X0: POSICION INICIAL
!V0: VELOCIDAD INICIAL
!XI:PORCENTAJE DE AMORTIGUAMIENTO
!A: ACELERACIÓN LEIDA 
!KD: RIGIDEZ DINÁMICA

    INTEGER:: I
	REAL:: T, BETA, GAMA, M,K, W,DT, C,XI,A(20000),KD

! COEFICIENTES
    REAL::A1,A2,A3
 
!!!!!VALORES DE SALIDA   
!F:FUERZA 
!FD:FUERZA DINÁMICA
!XR: DESPLAZAMIENTO RELATIVO
!VR: VELOCIDAD RELATIVA
!AR: ACELERACIÓN RELATIVA
!AT: ACELERACIÓN TOTAL

    REAL::F(20000),FD(20000), XR(20000),VR(20000),AR(20000), AT(20000)
    
!!!!!VARIABLES AUXILIARES
    INTEGER:: J, N
    REAL:: MR(20000,20000), x , y

!!!!!!DEFINICIÓN DE CONSTANTES
    
GAMA=0.5   !NO CAMBIA

!LECTURA DEL ARCHIVO DE ENTRADA
	OPEN(UNIT=11, FILE='CUIP.txt', STATUS='OLD', ACTION='READ')
	READ(11,*) 
	READ(11,*)XI
	READ(11,*) 
    READ(11,*)T
    READ(11,*)
    READ(11,*)BETA, M, I, DT 
    READ(11,*)
    READ(11,*)
    READ(11,*)
		DO j=1, I+1
		READ(11,*) x, A(J), y
		END DO
      
CLOSE(11)

!CÁLCULO DE K
W=(2*3.14159)/T
K=(W**2)*M

!CÁLCULO DE COEFICIENTE DE AMORTIGUAMIENTO
C=2*M*W*XI

!CÁLCULO DE LOS COEFICIENTES
A1=((M/(BETA*DT**2))+ GAMA*C/(BETA*DT))
A2=((M/(BETA*DT))+((GAMA/BETA)-1)*C)
A3=((((1/(2*BETA))-1)*M)+(C*DT)*((GAMA/(2*BETA))-1))

KD=K+A1
N=50
 
!CÁLCULO DEL VECTOR DE FUERZAS 
DO j=1, N
F(J)=A(J)*(-1)
END DO

!CÁLCULO DE VALORES INICIALES
FD(1)=F(1)
XR(1)=0
VR(1)=0
AR(1)=F(1)

!CÁLCULO DEL VECTOR DE FUERZA DINÁMICA, DE DESPLAZAMIENTOS RELATIVOS, DE VELOCIDAD RELATIVA Y DE ACELERACIÓN RELATIVA
DO J=1, N
  IF (J>1) THEN 
  FD(J)=F(J)+(A1*XR(J-1))+(A2*VR(J-1))+(A3*AR(J-1))
  XR(J)=FD(J)/KD
  VR(J)=(GAMA/(BETA*DT))*(XR(J)-XR(J-1))+(1-(GAMA/BETA))*VR(J-1)+(1-(GAMA/(2*BETA)))*DT*AR(J-1)
  AR(J)=(1/(BETA*DT**2))*(XR(J)-XR(J-1))-((1/(BETA*DT))*VR(J-1))-(((1/(2*BETA))-1)*AR(J-1))
  END IF
END DO


!CÁLCULO DEL VECTOR DE ACELERACIONES TOTALES
DO j=1, N
AT(J)=AR(J)+A(J)
END DO

!CREACIÓN DE MATRIZ DE RESULTADOS
DO j=1, N
  MR (J,1)=F(J)
  MR (J,2)=FD(J)
  MR (J,3)=XR(J)
  MR (J,4)=VR(J)
  MR (J,5)=AR(J)
  MR (J,6)=AT(J)
END DO



PRINT*, FD(2), XR(2),K, KD ,A1, A2, A3, C, M, DT, AT(3), (C)

  PRINT*, '   RESULTADOS ' 
  PRINT*, '         I          F            FD             XR            VR            AR             AT'
DO J=1, N
  PRINT*, J*DT, F(J), FD(J), XR(J), VR(J), AR(J),AT(J)
END DO 


!IMPRIMIENDO RESULTADOS EN UN ARCHIVO "RESULTADOS.TXT".

	OPEN(UNIT=11, FILE="RESULTADOS.txt", STATUS="REPLACE", ACTION="WRITE")
	WRITE(11,*) '     '
	WRITE(11,*) '                                                    RESULTADOS'
	WRITE(11,*) "    "

	
WRITE(11,*) "     "
	WRITE(11,*) "    " 
    WRITE(11,*)'         I              F              FD               XR               VR               AR                AT'
		DO J=1, N 
		WRITE(11,*)J*DT, F(J), FD(J), XR(J), VR(J), AR(J),AT(J)
		END DO
CLOSE(11)
        
END PROGRAM TAREA_3_DEA